apiVersion: apps/v1
kind: Deployment
metadata:
  name: reporting-service
  namespace: it-reporting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reporting-service
  template:
    metadata:
      labels:
        app: reporting-service
    spec:
      containers:
        - name: reporting-service
          image: devacr301225.azurecr.io/reporting-service:v1
          ports:
            - containerPort: 8083
          env:
            - name: ASSET_SERVICE_URL
              value: https://asset-service.it-asset.svc.cluster.local
            - name: EMPLOYEE_SERVICE_URL
              value: https://employee-service.it-employee.svc.cluster.local
            - name: ASSIGNMENT_SERVICE_URL
              value: https://assignment-service.it-assignment.svc.cluster.local

          # âœ… CORRECT HEALTH CHECKS
          readinessProbe:
            httpGet:
              path: /health
              port: 8083
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /health
              port: 8083
            initialDelaySeconds: 40
            periodSeconds: 20
